package dao;

import java.sql.*;
import java.util.*;
import models.*;

public class InventoryDao {
    public Employee findUser(Connection c,String email,String password) throws SQLException { String q="SELECT * FROM ITEM_USERS WHERE EMAIL=? AND USER_PASSWORD=? AND IS_ACTIVE=1"; try(PreparedStatement s=c.prepareStatement(q)){s.setString(1,email);s.setString(2,password);try(ResultSet r=s.executeQuery()){return r.next()?user(r):null;}}}
    public Employee findUserByEmail(Connection c,String email) throws SQLException {try(PreparedStatement s=c.prepareStatement("SELECT * FROM ITEM_USERS WHERE EMAIL=?")){s.setString(1,email);try(ResultSet r=s.executeQuery()){return r.next()?user(r):null;}}}
    public List<Category> categories(Connection c) throws SQLException {List<Category>x=new ArrayList<>();try(Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT * FROM CATEGORIES ORDER BY CATEGORY_NAME")){while(r.next()){Category a=new Category();a.id=r.getInt(1);a.name=r.getString(2);x.add(a);}}return x;}
    public List<Product> products(Connection c,int category) throws SQLException {List<Product>x=new ArrayList<>();String q="SELECT P.*,C.CATEGORY_NAME,D.DESCRIPTION,D.ISSUE_DATE,D.EXPIRY_DATE FROM PRODUCTS P JOIN CATEGORIES C ON P.CATEGORY_ID=C.CATEGORY_ID LEFT JOIN PRODUCT_DETAILS D ON P.PRODUCT_ID=D.PRODUCT_ID"+(category>0?" WHERE P.CATEGORY_ID=?":"")+" ORDER BY P.PRODUCT_ID DESC";try(PreparedStatement s=c.prepareStatement(q)){if(category>0)s.setInt(1,category);try(ResultSet r=s.executeQuery()){while(r.next())x.add(product(r));}}return x;}
    public Product product(Connection c,int id)throws SQLException{try(PreparedStatement s=c.prepareStatement("SELECT P.*,C.CATEGORY_NAME,D.DESCRIPTION,D.ISSUE_DATE,D.EXPIRY_DATE FROM PRODUCTS P JOIN CATEGORIES C ON P.CATEGORY_ID=C.CATEGORY_ID LEFT JOIN PRODUCT_DETAILS D ON P.PRODUCT_ID=D.PRODUCT_ID WHERE P.PRODUCT_ID=?")){s.setInt(1,id);try(ResultSet r=s.executeQuery()){return r.next()?product(r):null;}}}
    public void category(Connection c,String name)throws SQLException{try(PreparedStatement s=c.prepareStatement("INSERT INTO CATEGORIES(CATEGORY_NAME) VALUES(?)")){s.setString(1,name);s.executeUpdate();}}
    public void updateCategory(Connection c,int id,String name)throws SQLException{try(PreparedStatement s=c.prepareStatement("UPDATE CATEGORIES SET CATEGORY_NAME=? WHERE CATEGORY_ID=?")){s.setString(1,name);s.setInt(2,id);s.executeUpdate();}}
    public void deleteCategory(Connection c,int id)throws SQLException{try(PreparedStatement s=c.prepareStatement("DELETE FROM CATEGORIES WHERE CATEGORY_ID=?")){s.setInt(1,id);s.executeUpdate();}}
    public void saveProduct(Connection c,Product p)throws SQLException{if(p.id==0){try(PreparedStatement s=c.prepareStatement("INSERT INTO PRODUCTS(PRODUCT_NAME,CATEGORY_ID,PRICE,QUANTITY) VALUES(?,?,?,?)",new String[]{"PRODUCT_ID"})){s.setString(1,p.name);s.setInt(2,p.categoryId);s.setDouble(3,p.price);s.setInt(4,p.quantity);s.executeUpdate();try(ResultSet r=s.getGeneratedKeys()){r.next();p.id=r.getInt(1);}}}else{try(PreparedStatement s=c.prepareStatement("UPDATE PRODUCTS SET PRODUCT_NAME=?,CATEGORY_ID=?,PRICE=?,QUANTITY=? WHERE PRODUCT_ID=?")){s.setString(1,p.name);s.setInt(2,p.categoryId);s.setDouble(3,p.price);s.setInt(4,p.quantity);s.setInt(5,p.id);s.executeUpdate();}}try(PreparedStatement s=c.prepareStatement("MERGE INTO PRODUCT_DETAILS D USING DUAL ON (D.PRODUCT_ID=?) WHEN MATCHED THEN UPDATE SET DESCRIPTION=?,ISSUE_DATE=?,EXPIRY_DATE=? WHEN NOT MATCHED THEN INSERT(PRODUCT_ID,DESCRIPTION,ISSUE_DATE,EXPIRY_DATE) VALUES(?,?,?,?)")){s.setInt(1,p.id);s.setString(2,p.description);s.setDate(3,date(p.issueDate));s.setDate(4,date(p.expiryDate));s.setInt(5,p.id);s.setString(6,p.description);s.setDate(7,date(p.issueDate));s.setDate(8,date(p.expiryDate));s.executeUpdate();}}
    public void deleteProduct(Connection c,int id)throws SQLException{try(PreparedStatement s=c.prepareStatement("DELETE FROM PRODUCTS WHERE PRODUCT_ID=?")){s.setInt(1,id);s.executeUpdate();}}
    public List<Employee> employees(Connection c)throws SQLException{List<Employee>x=new ArrayList<>();try(Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT * FROM ITEM_USERS ORDER BY USER_ID")){while(r.next())x.add(user(r));}return x;}
    public void addEmployee(Connection c,Employee e)throws SQLException{try(PreparedStatement s=c.prepareStatement("INSERT INTO ITEM_USERS(FULL_NAME,PHONE_NUMBER,EMAIL,USER_PASSWORD,IS_ADMIN,CAN_UPDATE_PRODUCTS,CAN_DELETE_PRODUCTS,CAN_UPDATE_CATEGORIES,CAN_DELETE_CATEGORIES,IS_ACTIVE) VALUES(?,?,?,?,?,?,?,?,?,1)")){s.setString(1,e.name);s.setString(2,e.phone);s.setString(3,e.email);s.setString(4,e.password);s.setInt(5,e.admin?1:0);s.setInt(6,e.updateProducts?1:0);s.setInt(7,e.deleteProducts?1:0);s.setInt(8,e.updateCategories?1:0);s.setInt(9,e.deleteCategories?1:0);s.executeUpdate();}}
    public void updateEmployee(Connection c,Employee e)throws SQLException{String q="UPDATE ITEM_USERS SET FULL_NAME=?,PHONE_NUMBER=?,EMAIL=?,IS_ADMIN=?,CAN_UPDATE_PRODUCTS=?,CAN_DELETE_PRODUCTS=?,CAN_UPDATE_CATEGORIES=?,CAN_DELETE_CATEGORIES=?,IS_ACTIVE=? WHERE USER_ID=?";try(PreparedStatement s=c.prepareStatement(q)){s.setString(1,e.name);s.setString(2,e.phone);s.setString(3,e.email);s.setInt(4,e.admin?1:0);s.setInt(5,e.updateProducts?1:0);s.setInt(6,e.deleteProducts?1:0);s.setInt(7,e.updateCategories?1:0);s.setInt(8,e.deleteCategories?1:0);s.setInt(9,e.active?1:0);s.setInt(10,e.id);s.executeUpdate();}}
    public void deleteEmployee(Connection c,int id)throws SQLException{try(PreparedStatement s=c.prepareStatement("DELETE FROM ITEM_USERS WHERE USER_ID=? AND IS_ADMIN=0")){s.setInt(1,id);s.executeUpdate();}}
    public void password(Connection c,int id,String p)throws SQLException{try(PreparedStatement s=c.prepareStatement("UPDATE ITEM_USERS SET USER_PASSWORD=? WHERE USER_ID=?")){s.setString(1,p);s.setInt(2,id);s.executeUpdate();}}
    private Employee user(ResultSet r)throws SQLException{Employee e=new Employee();e.id=r.getInt("USER_ID");e.name=r.getString("FULL_NAME");e.phone=r.getString("PHONE_NUMBER");e.email=r.getString("EMAIL");e.password=r.getString("USER_PASSWORD");e.admin=r.getInt("IS_ADMIN")==1;e.updateProducts=r.getInt("CAN_UPDATE_PRODUCTS")==1;e.deleteProducts=r.getInt("CAN_DELETE_PRODUCTS")==1;e.updateCategories=r.getInt("CAN_UPDATE_CATEGORIES")==1;e.deleteCategories=r.getInt("CAN_DELETE_CATEGORIES")==1;e.active=r.getInt("IS_ACTIVE")==1;return e;}
    private Product product(ResultSet r)throws SQLException{Product p=new Product();p.id=r.getInt("PRODUCT_ID");p.name=r.getString("PRODUCT_NAME");p.categoryId=r.getInt("CATEGORY_ID");p.categoryName=r.getString("CATEGORY_NAME");p.price=r.getDouble("PRICE");p.quantity=r.getInt("QUANTITY");p.description=r.getString("DESCRIPTION");java.sql.Date i=r.getDate("ISSUE_DATE"),e=r.getDate("EXPIRY_DATE");p.issueDate=i==null?"":i.toString();p.expiryDate=e==null?"":e.toString();return p;}
    private java.sql.Date date(String x){return x==null||x.trim().isEmpty()?null:java.sql.Date.valueOf(x);}
}
