<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ page import="java.util.List,java.text.DecimalFormat,models.Product,models.Category,models.Employee" %>
<%! String h(String v){if(v==null)return "";return v.replace("&","&amp;").replace("\"","&quot;").replace("<","&lt;").replace(">","&gt;");} %>
<% List<Product> products=(List<Product>)request.getAttribute("products"); List<Category> categories=(List<Category>)request.getAttribute("categories"); Employee user=(Employee)session.getAttribute("currentUser"); DecimalFormat money=new DecimalFormat("#,##0.00"); %>
<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Products - Item Project</title><link rel="stylesheet" href="<%=request.getContextPath()%>/assets/css/style.css"><link rel="stylesheet" href="<%=request.getContextPath()%>/assets/css/app-layout.css"><link rel="stylesheet" href="<%=request.getContextPath()%>/assets/css/product-form.css"></head>
<body class="app-body"><%@ include file="/WEB-INF/jspf/sidebar.jspf" %><main class="app-main"><header class="page-header"><div><span class="page-kicker">Inventory</span><h1>Products</h1><p>Review stock, pricing, and product details in one place.</p></div><% if(categories!=null&&!categories.isEmpty()){ %><button class="primary-button compact" type="button" data-modal-open="productModal">Add product</button><% } %></header>
<% if(request.getAttribute("message")!=null){ %><div class="alert"><%=h(String.valueOf(request.getAttribute("message")))%></div><% } %>
<section class="toolbar"><form method="get" action="<%=request.getContextPath()%>/products"><label class="filter-label">Category<select name="category" onchange="this.form.submit()"><option value="0">All categories</option><% int selected=(Integer)request.getAttribute("selectedCategory");for(Category c:categories){ %><option value="<%=c.id%>" <%=selected==c.id?"selected":""%>><%=h(c.name)%></option><% } %></select></label></form><label class="table-search"><svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m16 16 5 5"/></svg><input type="search" placeholder="Search products" data-table-search></label></section>
<section class="table-card"><% if(products==null||products.isEmpty()){ %><div class="empty-state"><div class="empty-icon">+</div><h2>No products yet</h2><p>Start by adding your first product to the inventory.</p><% if(categories==null||categories.isEmpty()){ %><button class="primary-button" data-modal-open="categoryModal">Add a category first</button><% }else{ %><button class="primary-button" data-modal-open="productModal">Add product</button><% } %></div><% }else{ %><div class="table-wrap"><table><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Quantity</th><th>Status</th><th>Actions</th></tr></thead><tbody><% for(Product p:products){ %><tr data-search-row data-search-value="<%=h((p.name+" "+p.categoryName).toLowerCase())%>"><td><div class="product-cell"><span><%=h(p.name.substring(0,1).toUpperCase())%></span><strong><%=h(p.name)%></strong></div></td><td><span class="category-pill"><%=h(p.categoryName)%></span></td><td>$ <%=money.format(p.price)%></td><td><%=p.quantity%></td><td><span class="stock-status <%=p.quantity==0?"out":p.quantity<10?"low":""%>"><%=p.quantity==0?"Out of stock":p.quantity<10?"Low stock":"In stock"%></span></td><td><div class="action-row"><button class="details-button" type="button" data-details data-name="<%=h(p.name)%>" data-category="<%=h(p.categoryName)%>" data-price="<%=p.price%>" data-quantity="<%=p.quantity%>" data-description="<%=h(p.description)%>" data-issue="<%=h(p.issueDate)%>" data-expiry="<%=h(p.expiryDate)%>">Details</button><% if(user.admin||user.updateProducts){ %><button class="icon-action" type="button" title="Edit product" data-edit-product data-id="<%=p.id%>" data-name="<%=h(p.name)%>" data-category-id="<%=p.categoryId%>" data-price="<%=p.price%>" data-quantity="<%=p.quantity%>" data-description="<%=h(p.description)%>" data-issue="<%=h(p.issueDate)%>" data-expiry="<%=h(p.expiryDate)%>"><svg viewBox="0 0 24 24"><path d="m4 16-1 5 5-1L19 9l-4-4Z"/><path d="m13 7 4 4"/></svg></button><% } if(user.admin||user.deleteProducts){ %><form action="<%=request.getContextPath()%>/products" method="post" data-confirm="Delete this product permanently?"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<%=p.id%>"><button class="icon-action danger" type="submit" title="Delete product"><svg viewBox="0 0 24 24"><path d="M4 7h16M9 7V4h6v3M7 7l1 14h8l1-14M10 11v6M14 11v6"/></svg></button></form><% } %></div></td></tr><% } %></tbody></table></div><% } %></section></main>
<dialog class="modal" id="categoryModal"><form method="post" action="<%=request.getContextPath()%>/categories"><input type="hidden" name="returnTo" value="products"><div class="modal-header"><div><span>New category</span><h2>Add category</h2></div><button class="modal-close" type="button" data-modal-close>×</button></div><label>Category name<input name="name" maxlength="120" required autofocus></label><div class="modal-actions"><button class="secondary-button" type="button" data-modal-close>Cancel</button><button class="primary-button compact" type="submit">Add category</button></div></form></dialog>
<% if(categories!=null&&!categories.isEmpty()){ %>
<dialog class="modal product-modal" id="productModal">
    <form method="post" action="<%=request.getContextPath()%>/products" data-product-form novalidate>
        <input type="hidden" name="id" value="0">
        <div class="modal-header"><div><span data-product-subtitle>Step 1 of 2</span><h2 data-product-title>Add product</h2></div><button class="modal-close" type="button" data-modal-close>×</button></div>
        <div class="step-indicator"><span class="active"></span><span></span></div>
        <section data-product-step="1">
            <div class="form-grid">
                <label class="wide">Product name<input name="name" maxlength="160" required></label>
                <label class="wide category-combobox">
                    Category
                    <div class="combobox" data-category-combobox>
                        <input type="text" name="categoryName" placeholder="Search or choose a category" autocomplete="off" required data-category-input>
                        <button class="category-toggle" type="button" data-category-toggle aria-label="Show categories"><svg viewBox="0 0 24 24"><path d="m6 9 6 6 6-6"/></svg></button>
                        <div class="category-options" data-category-options hidden><% for(Category c:categories){ %><button type="button" class="category-option" data-category-option data-id="<%=c.id%>" data-name="<%=h(c.name)%>"><span><%=h(c.name)%></span><svg viewBox="0 0 24 24"><path d="M5 12h14"/></svg></button><% } %></div>
                    </div>
                    <input type="hidden" name="categoryId" data-category-id>
                </label>
                <label>Price<input name="price" type="number" min="0" step="0.01" required></label>
                <label>Quantity<input name="quantity" type="number" min="0" required></label>
            </div>
            <div class="modal-actions"><button class="secondary-button" type="button" data-modal-close>Cancel</button><button class="primary-button compact" type="button" data-next-step>Next</button></div>
        </section>
        <section hidden data-product-step="2">
            <div class="optional-note"><strong>Product details</strong><span>Optional — you can save without completing these fields.</span></div>
            <div class="form-grid"><label class="wide">Description<textarea name="description" rows="5" maxlength="1000"></textarea></label><label>Issue date<input name="issueDate" type="date"></label><label>Expiry date<input name="expiryDate" type="date"></label></div>
            <div class="modal-actions"><button class="secondary-button" type="button" data-previous-step>Back</button><button class="primary-button compact" type="submit">Save</button></div>
        </section>
    </form>
</dialog>
<% } %>
<dialog class="modal details-modal" id="detailsModal"><div class="modal-header"><div><span>Product details</span><h2 data-detail-name></h2></div><button class="modal-close" type="button" data-modal-close>×</button></div><div class="detail-grid"><div><span>Category</span><strong data-detail-category></strong></div><div><span>Price</span><strong data-detail-price></strong></div><div><span>Quantity</span><strong data-detail-quantity></strong></div><div class="wide"><span>Description</span><p data-detail-description></p></div><div><span>Issue date</span><strong data-detail-issue></strong></div><div><span>Expiry date</span><strong data-detail-expiry></strong></div></div></dialog>
<script src="<%=request.getContextPath()%>/assets/js/main.js"></script></body></html>
