CREATE USER ITEM_PROJECT_USER IDENTIFIED BY "ItemProject@123";

GRANT CREATE SESSION TO ITEM_PROJECT_USER;
GRANT CREATE TABLE TO ITEM_PROJECT_USER;
GRANT CREATE SEQUENCE TO ITEM_PROJECT_USER;

ALTER USER ITEM_PROJECT_USER QUOTA UNLIMITED ON USERS;
