INSERT INTO ITEM_USERS
    (FULL_NAME, PHONE_NUMBER, EMAIL, USER_PASSWORD, IS_ADMIN, CAN_UPDATE_PRODUCTS, CAN_DELETE_PRODUCTS, CAN_UPDATE_CATEGORIES, CAN_DELETE_CATEGORIES, IS_ACTIVE)
VALUES
    ('Ahmed Elgaml', '+201000000000', 'ahmedelgaml353@gmail.com', 'Ahmedali123@#', 1, 1, 1, 1, 1, 1);

COMMIT;
