

CREATE USER EWALLET_USER IDENTIFIED BY "Ewallet@123";

GRANT CREATE SESSION TO EWALLET_USER;
GRANT CREATE TABLE TO EWALLET_USER;
GRANT CREATE SEQUENCE TO EWALLET_USER;
GRANT CREATE TRIGGER TO EWALLET_USER;

ALTER USER EWALLET_USER QUOTA UNLIMITED ON USERS;
