ALTER TABLE WALLET_TRANSACTIONS ADD (
    TRANSACTION_TYPE VARCHAR2(30),
    AMOUNT NUMBER(15, 2),
    RELATED_EMAIL VARCHAR2(120),
    DESCRIPTION VARCHAR2(500)
);

UPDATE WALLET_TRANSACTIONS
SET TRANSACTION_TYPE = 'LOGIN',
    AMOUNT = 0,
    DESCRIPTION = TRANSACTION_TEXT;

ALTER TABLE WALLET_TRANSACTIONS MODIFY (
    TRANSACTION_TYPE NOT NULL,
    AMOUNT DEFAULT 0 NOT NULL,
    DESCRIPTION NOT NULL
);

ALTER TABLE WALLET_TRANSACTIONS DROP COLUMN TRANSACTION_TEXT;

ALTER TABLE WALLET_TRANSACTIONS ADD CONSTRAINT CHECK_TRANSACTION_TYPE CHECK (
    TRANSACTION_TYPE IN ('SIGNUP', 'LOGIN', 'DEPOSIT', 'WITHDRAW', 'TRANSFER_SENT',
        'TRANSFER_RECEIVED', 'PASSWORD_CHANGE', 'ACCOUNT_INACTIVE')
);

ALTER TABLE WALLET_TRANSACTIONS ADD CONSTRAINT CHECK_TRANSACTION_AMOUNT CHECK (AMOUNT >= 0);
