ALTER TABLE WALLET_ACCOUNTS RENAME COLUMN USER_NAME TO EMAIL;

UPDATE WALLET_ACCOUNTS
SET EMAIL = LOWER(EMAIL) || '@legacy.local'
WHERE INSTR(EMAIL, '@') = 0;

ALTER TABLE WALLET_ACCOUNTS MODIFY EMAIL VARCHAR2(120);
